// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: houses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createHouse = `-- name: CreateHouse :one
INSERT INTO houses (location,block,partition, occupied) VALUES ($1,$2,$3,$4) RETURNING house_id
`

type CreateHouseParams struct {
	Location  string `json:"location"`
	Block     string `json:"block"`
	Partition int16  `json:"partition"`
	Occupied  bool   `json:"occupied"`
}

func (q *Queries) CreateHouse(ctx context.Context, arg CreateHouseParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createHouse,
		arg.Location,
		arg.Block,
		arg.Partition,
		arg.Occupied,
	)
	var house_id uuid.UUID
	err := row.Scan(&house_id)
	return house_id, err
}

const getHouseById = `-- name: GetHouseById :one
SELECT house_id,location, block, partition , Occupied FROM houses
WHERE house_id = $1
`

func (q *Queries) GetHouseById(ctx context.Context, houseID uuid.UUID) (House, error) {
	row := q.db.QueryRowContext(ctx, getHouseById, houseID)
	var i House
	err := row.Scan(
		&i.HouseID,
		&i.Location,
		&i.Block,
		&i.Partition,
		&i.Occupied,
	)
	return i, err
}

const getHouses = `-- name: GetHouses :many
SELECT house_id,location, block, partition , occupied FROM houses
`

func (q *Queries) GetHouses(ctx context.Context) ([]House, error) {
	rows, err := q.db.QueryContext(ctx, getHouses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []House{}
	for rows.Next() {
		var i House
		if err := rows.Scan(
			&i.HouseID,
			&i.Location,
			&i.Block,
			&i.Partition,
			&i.Occupied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHouseById = `-- name: UpdateHouseById :exec
UPDATE houses
SET occupied = $1
WHERE house_id = $2
`

type UpdateHouseByIdParams struct {
	Occupied bool      `json:"occupied"`
	HouseID  uuid.UUID `json:"house_id"`
}

func (q *Queries) UpdateHouseById(ctx context.Context, arg UpdateHouseByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateHouseById, arg.Occupied, arg.HouseID)
	return err
}
