// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: payments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (tenant_id,period,start_date,end_date, renewed) VALUES ($1,$2,$3,$4,$5)
`

type CreatePaymentParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	Period    int32     `json:"period"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Renewed   bool      `json:"renewed"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.TenantID,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
		arg.Renewed,
	)
	return err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payments WHERE payment_id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, paymentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePayment, paymentID)
	return err
}

const getAllPayments = `-- name: GetAllPayments :many
SELECT payment_id,tenant_id, period, start_date, end_date, renewed FROM payments
`

type GetAllPaymentsRow struct {
	PaymentID uuid.UUID `json:"payment_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Period    int32     `json:"period"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Renewed   bool      `json:"renewed"`
}

func (q *Queries) GetAllPayments(ctx context.Context) ([]GetAllPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllPaymentsRow{}
	for rows.Next() {
		var i GetAllPaymentsRow
		if err := rows.Scan(
			&i.PaymentID,
			&i.TenantID,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.Renewed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentById = `-- name: GetPaymentById :one
SELECT payment_id,tenant_id, period, start_date, end_date, renewed FROM payments 
WHERE payment_id = $1
`

type GetPaymentByIdRow struct {
	PaymentID uuid.UUID `json:"payment_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Period    int32     `json:"period"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Renewed   bool      `json:"renewed"`
}

func (q *Queries) GetPaymentById(ctx context.Context, paymentID uuid.UUID) (GetPaymentByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentById, paymentID)
	var i GetPaymentByIdRow
	err := row.Scan(
		&i.PaymentID,
		&i.TenantID,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.Renewed,
	)
	return i, err
}

const getUnrenewedByTenantId = `-- name: GetUnrenewedByTenantId :one
SELECT payment_id,tenant_id, period, start_date, end_date, renewed FROM payments 
WHERE renewed = false and tenant_id = $1
`

type GetUnrenewedByTenantIdRow struct {
	PaymentID uuid.UUID `json:"payment_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Period    int32     `json:"period"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Renewed   bool      `json:"renewed"`
}

func (q *Queries) GetUnrenewedByTenantId(ctx context.Context, tenantID uuid.UUID) (GetUnrenewedByTenantIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUnrenewedByTenantId, tenantID)
	var i GetUnrenewedByTenantIdRow
	err := row.Scan(
		&i.PaymentID,
		&i.TenantID,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.Renewed,
	)
	return i, err
}

const updatePayment = `-- name: UpdatePayment :exec
UPDATE payments
SET period = $1, start_date = $2, end_date = $3, renewed = $4
WHERE payment_id = $5
`

type UpdatePaymentParams struct {
	Period    int32     `json:"period"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Renewed   bool      `json:"renewed"`
	PaymentID uuid.UUID `json:"payment_id"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, updatePayment,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
		arg.Renewed,
		arg.PaymentID,
	)
	return err
}
