// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateHouse(ctx context.Context, arg CreateHouseParams) (uuid.UUID, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) error
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	DeleteAllToken(ctx context.Context, arg DeleteAllTokenParams) error
	DeletePayment(ctx context.Context, paymentID uuid.UUID) error
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetAllPayments(ctx context.Context) ([]GetAllPaymentsRow, error)
	GetForTokenAdmin(ctx context.Context, arg GetForTokenAdminParams) (Admin, error)
	GetHouseById(ctx context.Context, houseID uuid.UUID) (House, error)
	GetHouses(ctx context.Context) ([]House, error)
	GetPaymentById(ctx context.Context, paymentID uuid.UUID) (GetPaymentByIdRow, error)
	GetTenantById(ctx context.Context, tenantID uuid.UUID) (GetTenantByIdRow, error)
	GetTenants(ctx context.Context) ([]GetTenantsRow, error)
	GetUnrenewedByTenantId(ctx context.Context, tenantID uuid.UUID) (GetUnrenewedByTenantIdRow, error)
	InsertAdmin(ctx context.Context, arg InsertAdminParams) (InsertAdminRow, error)
	UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (int32, error)
	UpdateHouseById(ctx context.Context, arg UpdateHouseByIdParams) error
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) error
}

var _ Querier = (*Queries)(nil)
